name: biblio_tech_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_nfc_kit: ^3.4.1
  flutter_riverpod: ^2.4.6
  flutter_speed_dial: ^7.0.0
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  intl: ^0.19.0
  nfc_manager: ^3.3.0
  test: ^1.24.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/loaders/
  fonts:
    - family: Bangers
      fonts:
        - asset: fonts/Bangers/Bangers-Regular.ttf

    
